spring.application.name=backend


# DB
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/compileit_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yor_mail_id
spring.mail.password=yor_project_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com

jwt.secret=your_own_secret_key


